version: "3"

services:
  app:
    build: .
    ports:
      - "3010:3010"
      - "3011:3011"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
